swagger: '2.0'
info:
  title: Smartlocker API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /sessions:
    post:
      operationId: api.sessions.create
      tags:
        - Session
      summary: >-
        Creates a new session. If other session exists for the same user, delete
        it
      parameters:
        - name: email
          description: user e-mail
          in: header
          type: string
          required: true
        - name: password
          description: user password
          in: header
          type: string
          format: password
          required: true
      responses:
        '200':
          description: Session created
          schema:
            type: array
            items:
              $ref: '#/definitions/Session'
        '400':
          description: Invalid user or password

definitions:
  Session:
    type: object
    properties:
      token:
        type: string
      email:
        type: string
      expiration:
        type: string
        format: date-time
