swagger: "2.0"

info:
  title: "Smar Locker API"
  version: "1.0"

paths:
  /lockersets/:
    get:
      responses:
        '200':
          description: 'Fetch a list of lockersets'
          schema:
            type: array
            items:
              $ref: '#/definitions/Lockerset'

definitions:
  Lockerset:
    type: object
    properties:
      id:
        type: integer
        format: int64
      code: { type: string }
      numBoxes: { type: integer }
